services:
  api:
    container_name: habit_tracker_test
    environment: 
      - PGUSER=getbaked
      - PGHOST=db
      - PGPASSWORD=habitspass
      - PGDATABASE=habits_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: hobbit_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habits_test
      - POSTGRES_PASSWORD=habitspass
volumes:
  test_db:
networks: 
  default:
    name: habit_tracker_test